import CoreImage
import Foundation

/// Measured linear-sRGB to linear-sRGB correction. Coefficient order per row:
/// R, G, B, sqrt(RG), sqrt(GB), sqrt(RB). No intercept: C(kx) = k C(x).
/// Coefficients are imported instrument data, never generated by the style AI.
public struct PhotoColorCalibration: Codable, Equatable, Sendable {
    public enum Stage: String, Codable, Sendable { case input, output }
    public let version: Int
    public let name: String
    public let provenance: String
    public let workingSpace: String
    public let stage: Stage
    public let rows: [[Double]]

    public init(name: String, provenance: String, stage: Stage, rows: [[Double]]) throws {
        version = 1; self.name = name; self.provenance = provenance
        workingSpace = "extendedLinearSRGB"; self.stage = stage; self.rows = rows
        try validate()
    }
    private enum CodingKeys: String, CodingKey { case version, name, provenance, workingSpace, stage, rows }
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        version = try c.decode(Int.self, forKey: .version)
        name = try c.decode(String.self, forKey: .name)
        provenance = try c.decode(String.self, forKey: .provenance)
        workingSpace = try c.decode(String.self, forKey: .workingSpace)
        stage = try c.decode(Stage.self, forKey: .stage)
        rows = try c.decode([[Double]].self, forKey: .rows)
        try validate()
    }
    private func validate() throws {
        guard version == 1, workingSpace == "extendedLinearSRGB",
              !name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, name.count <= 160,
              !provenance.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, provenance.count <= 4000,
              rows.count == 3, rows.allSatisfy({ $0.count == 6 && $0.allSatisfy { $0.isFinite && abs($0) <= 16 } }) else {
            throw NSError(domain: "PhotoColorCalibration", code: 1, userInfo: [NSLocalizedDescriptionKey:
                "校準檔必須包含線性 sRGB 工作空間、來源、套用階段及有效的 3×6 係數。"])
        }
    }
    public func reference(_ rgb: SIMD3<Double>) -> SIMD3<Double> {
        // Root-polynomial features are defined on nonnegative sensor responses.
        // Extended-gamut negative channels bypass calibration, without clipping.
        guard (0..<3).allSatisfy({ rgb[$0].isFinite && rgb[$0] >= 0 }) else { return rgb }
        let f = [rgb.x, rgb.y, rgb.z, sqrt(rgb.x) * sqrt(rgb.y), sqrt(rgb.y) * sqrt(rgb.z), sqrt(rgb.x) * sqrt(rgb.z)]
        return SIMD3((0..<3).map { i in zip(rows[i], f).reduce(0) { $0 + $1.0 * $1.1 } })
    }
}

public enum PhotoColorCalibrationProcessor {
    private static let space = CGColorSpace(name: CGColorSpace.extendedLinearSRGB)!
    public static func apply(to image: CIImage, calibration: PhotoColorCalibration?) -> CIImage {
        guard let calibration, let kernel, let linear = image.matchedFromWorkingSpace(to: space) else { return image }
        let arguments: [Any] = [linear] + calibration.rows.flatMap { row -> [Any] in
            [CIVector(x: row[0], y: row[1], z: row[2]), CIVector(x: row[3], y: row[4], z: row[5])]
        }
        guard let result = kernel.apply(extent: image.extent, arguments: arguments) else { return image }
        return result.matchedToWorkingSpace(from: space) ?? image
    }
    static var kernelIsAvailable: Bool { kernel != nil }
    private static let kernel: CIColorKernel? = {
        let code = """
        #include <metal_stdlib>
        #include <CoreImage/CoreImage.h>
        using namespace metal; using namespace coreimage;
        [[ stitchable ]] float4 rootPolynomial(sample_t p, float3 r0, float3 r1,
            float3 g0, float3 g1, float3 b0, float3 b1) {
            if (!(p.a > 0.0)) return p;
            float3 x = p.rgb / p.a;
            if (any(x < 0.0) || !all(isfinite(x))) return p;
            float3 roots = sqrt(x);
            float3 cross = float3(roots.x * roots.y, roots.y * roots.z, roots.x * roots.z);
            float3 result = float3(dot(r0,x)+dot(r1,cross), dot(g0,x)+dot(g1,cross), dot(b0,x)+dot(b1,cross));
            return float4(result * p.a, p.a);
        }
        """
        return (try? CIKernel.kernels(withMetalString: code))?.first as? CIColorKernel
    }()
}
